import { useEffect, useState } from "react";
import { loadDispositions } from "./lib/loadDispositions";
import type { VialRow } from "./types";
import { StatTiles } from "./components/StatTiles";
import { DispositionChart } from "./components/DispositionChart";
import { RadiusHistogram } from "./components/RadiusHistogram";
import { VialTable } from "./components/VialTable";
import "./App.css";

const DATA_URL = `${import.meta.env.BASE_URL}data/vial_disposition.csv`;

export default function App() {
  const [rows, setRows] = useState<VialRow[] | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    loadDispositions(DATA_URL)
      .then(setRows)
      .catch((err: Error) => setError(err.message));
  }, []);

  return (
    <div className="page">
      <header className="page-header">
        <h1>Vial Tracking Dashboard</h1>
        <p className="subtitle">
          Interactive view of the tracker + analytics output from{" "}
          <a href="https://github.com/manuelbomi/Vial-Tracking-on-Industrial-Accumulator-Table" target="_blank" rel="noreferrer">
            Vial-Tracking-on-Industrial-Accumulator-Table
          </a>
          . Reads <code>vial_disposition.csv</code>, the CSV{" "}
          <code>vial_analytics.py</code> writes for every run.
        </p>
      </header>

      <section className="panel">
        <img
          className="hero-image"
          src={`${import.meta.env.BASE_URL}images/before_after_tracking.png`}
          alt="Raw input frame next to the same frame after detection and persistent tracking, with stable per-vial IDs and colors"
        />
      </section>

      {error && <p className="error">Could not load {DATA_URL}: {error}</p>}

      {rows && (
        <>
          <section className="panel">
            <StatTiles rows={rows} />
          </section>

          <section className="panel chart-grid">
            <DispositionChart rows={rows} />
            <RadiusHistogram rows={rows} />
          </section>

          <section className="panel">
            <VialTable rows={rows} />
          </section>
        </>
      )}

      {!rows && !error && <p className="loading">Loading tracking data...</p>}

      <footer className="page-footer">
        <p>
          Sample data generated by <code>generate_sample_video.py</code> +{" "}
          <code>vial_persistent_tracker.py</code> + <code>vial_analytics.py</code>. Point{" "}
          <code>npm run sync-data</code> (see dashboard/README.md) at a fresh{" "}
          <code>analytics_output/vial_disposition.csv</code> to view your own run.
        </p>
      </footer>
    </div>
  );
}
